<?php
// Database Configuration Example
// Copy this file to config.php and update with your actual credentials
// Generated by Admin Portal

define('DB_HOST', 'localhost');
define('DB_NAME', 'hope_connect');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_PORT', '3306');

// Application Settings
define('APP_NAME', 'Hope Connect');
define('APP_ENV', 'production'); // development, staging, production
define('APP_URL', 'https://hopeconnect.org');

// Security Settings
define('SESSION_LIFETIME', 3600); // 1 hour in seconds
define('PASSWORD_MIN_LENGTH', 8);
define('ENABLE_2FA', false);

// Email Configuration
define('MAIL_HOST', 'smtp.example.com');
define('MAIL_PORT', 587);
define('MAIL_USERNAME', 'noreply@hopeconnect.org');
define('MAIL_PASSWORD', '');
define('MAIL_FROM', 'noreply@hopeconnect.org');
define('MAIL_FROM_NAME', 'Hope Connect');

// File Upload Settings
define('MAX_UPLOAD_SIZE', 5242880); // 5MB in bytes
define('ALLOWED_UPLOAD_TYPES', 'jpg,jpeg,png,pdf,doc,docx');

// API Keys (if needed)
define('GOOGLE_MAPS_API_KEY', '');
define('TWILIO_ACCOUNT_SID', '');
define('TWILIO_AUTH_TOKEN', '');

// Feature Flags
define('ENABLE_MESSAGING', true);
define('ENABLE_NOTIFICATIONS', true);
define('ENABLE_FILE_UPLOAD', true);

// Create database connection
try {
    $dsn = "mysql:host=" . DB_HOST . ";port=" . DB_PORT . ";dbname=" . DB_NAME . ";charset=utf8mb4";
    $options = [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ];
    $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
} catch(PDOException $e) {
    error_log("Database Connection Error: " . $e->getMessage());
    if (APP_ENV === 'development') {
        die("Database connection failed: " . $e->getMessage());
    } else {
        die("Database connection failed. Please contact support.");
    }
}

// Session Configuration
ini_set('session.cookie_httponly', 1);
ini_set('session.use_only_cookies', 1);
ini_set('session.cookie_secure', 1); // Set to 1 if using HTTPS
session_start();

// Timezone
date_default_timezone_set('America/New_York');

// Error Reporting
if (APP_ENV === 'development') {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
}
?>
